services:
  xtream2m3u:
    image: ghcr.io/ovosimpatico/xtream2m3u:latest
    container_name: xtream2m3u
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    restart: unless-stopped