name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      universal_macos:
        description: "xtream2m3u"
        required: false
        default: "false"
      release:
        description: "Push a new release"
        required: false
        default: "true"
      version:
        description: "Version"
        required: false
        version: 1.0.0
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}:latest
